development:
  adapter: postgresql
  encoding: unicode
  database: shopify_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: shopify_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: shopify_development
  pool: 5
  username: postgres
